data_shape: [4, 48, 84, 5] # (n_bars, n_timesteps, n_pitches, n_tracks) [4,48,84,5]  whole steps=4*48
beat_resolution: 12 # number of time steps used to represent a beat **bar** -- 12 4/4 
latent_dim: 128
is_conditional: false
is_accompaniment: true
condition_track_idx: 1
use_binary_neurons: true
nets:
  generator: accompaniment
  discriminator: default
